export {
  beginSession,
  changePassword,
  createUserKeyset,
  decryptField,
  encryptField,
  isEncryptedField,
  issueRecoveryKey,
  KeyHierarchyError,
  normalizeRecoveryKey,
  resetPasswordWithRecoveryKey,
  resumeSession,
  type UserKeyset,
  unlockWithPassword,
  unlockWithRecoveryKey,
} from "./key-hierarchy";
